# Generated by Django 5.2.4 on 2025-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_image/defualt_pro.png",
                upload_to="profile_image",
            ),
        ),
    ]
