# Generated by Django 5.2.4 on 2025-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default.png', null=True, upload_to='event_asset'),
        ),
    ]
